name: Build and Deploy to GKE

on:
  push:
    branches:
      - main
      - dev

jobs:
  setup-build-publish-deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'production' || 'development' }}

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
      GAR_LOCATION: us-east1
      GKE_CLUSTER: ${{ github.ref_name == 'main' && 'inventory-cloudbuild' || 'inventory-dev-cluster' }}
      GKE_ZONE: ${{ github.ref_name == 'main' && 'us-east1-c' || 'us-east1-c' }}
      K8S_NAMESPACE: ${{ github.ref_name == 'main' && 'prod' || 'dev' }}
      REPOSITORY: docker-repository
      IMAGE: inventory-app

    steps:
      - uses: actions/checkout@v4

      - uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - uses: google-github-actions/get-gke-credentials@v2
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GKE_ZONE }}

      - name: Build
        run: |
          docker build -t "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.ref_name }}-${{ github.sha }}" .

      - name: Publish
        run: |
          docker push "${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.ref_name }}-${{ github.sha }}"

      - name: Deploy
        run: |
          kubectl create namespace "${{ env.K8S_NAMESPACE }}" --dry-run=client -o yaml | kubectl apply -f -
          kubectl apply -n "${{ env.K8S_NAMESPACE }}" -f deployment-db-with-data.yaml
          kubectl apply -n "${{ env.K8S_NAMESPACE }}" -f app-deployment.yaml
          kubectl set image -n "${{ env.K8S_NAMESPACE }}" deployment/inventory-app-deployment inventory-app="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.IMAGE }}:${{ github.ref_name }}-${{ github.sha }}"
          kubectl rollout status -n "${{ env.K8S_NAMESPACE }}" deployment/inventory-app-deployment
          kubectl get pods -n "${{ env.K8S_NAMESPACE }}"
